name: FArhan Ali

on: 
 push:
   branches: [ main ]

jobs:
  build-nxtjs-file:
   runs-on: ubuntu-latest

   steps:
     - name: checkout repo
       uses: actions/checkout@v6.0.2
       
     - name: install node JS
       uses: actions/setup-node@v6.3.0
       with:
        node-version: 22.x
        cache: 'npm'

     - name: install dependencies
       run: npm install
       
     - name: build nxtjs file
       run: npm run build

     - name: saving build on artifacts
       uses: actions/upload-artifact@v3.2.2
       with:
         name: build artifacts
         path: out/
        
